spring.application.name=pruebas_integracion

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA: Flyway crea las tablas; Hibernate solo valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true